
% READ EARTH ORIENTATION PARAMETERS (EOP) FROM INTERNATIONAL EARTH ROTATION SERVICE (IERS) DATA FILES
% ---------------------------------------------------------------------------------------------------------------------
% Function reads Earth Orientation Parameters from single combined data file generated by combine_EOP.m and generates 
% a combined table which can be interpolated by the EOP.m function to retrieve EOP at date of interest. The first line 
% of the combined file contains the number of rows of data, the data begins on the second row. 
%
% Author: Matthew Buckhout
% Updated: 08/24/2020 
%
% Earth Orientation Parameter Data from IERS 
%     https://www.iers.org/IERS/EN/DataProducts/EarthOrientationData/eop.html
%
% Local filename: "IERS_EOP_combined.txt"
%
%     Data Format:
%     ----------------------------------------------------------------------------------------------------------
%      MJD(UT1)     yr           mo       d     xp (")   yp (")   UT1-UTC (sec)  UT1-TAI (sec)  TAI-UTC (sec)
%     ----------------------------------------------------------------------------------------------------------
%      48622.000000 1992.000000 1.000000 1.000000 0.182987 0.168775 -0.125166      -26.199424     26.074258
%      48623.000000 1992.000000 1.000000 2.000000 0.180614 0.166776 -0.126955      -26.201957     26.075002
%      48624.000000 1992.000000 1.000000 3.000000 0.178183 0.164804 -0.128700      -26.204490     26.075790
%      48625.000000 1992.000000 1.000000 4.000000 0.175821 0.162834 -0.130467      -26.207022     26.076556
%      48626.000000 1992.000000 1.000000 5.000000 0.173528 0.160861 -0.132317      -26.209555     26.077239
%      48627.000000 1992.000000 1.000000 6.000000 0.171271 0.158881 -0.134296      -26.212088     26.077792
%     ----------------------------------------------------------------------------------------------------------
%
%     Output Format [EOPdata]:
%     -------------------------------------------------------------------------------------------------
%      MJD(UT1)     yr  mo  d     xp (")      yp (")    UT1-UTC (sec)    UT1-TAI (sec)    TAI-UTC (sec)
%     -------------------------------------------------------------------------------------------------

function [EOPdata] = getdata_EOP_fast()
   
   % Earth Orientation Parameters
   fid = fopen('IERS_EOP_combined.txt','r');
   row1 = fscanf(fid, '%f %f %f %f %f %f %f %f %f', [9, 1]); %First row containing number of rows in data file
   EOPdata = zeros(row1(1),9);
   EOPdata = fscanf(fid, '%f %f %f %f %f %f %f %f %f', [9, row1(1)]);
   EOPdata = transpose(EOPdata);
   fclose(fid);
   
end